# This GitHub Action workflow file will build your Gradle project.
#
# To use this file, create a directory named `.github/workflows` in the root of your repository,
# and save this file as `gradle-build.yml` inside it.

name: Gradle Build

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the Java Development Kit (JDK)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Set up Gradle
      # This action caches Gradle dependencies and wrappers for faster builds.
      - name: Set up Gradle
        uses: actions/setup-gradle@v3

      # Step 4: Make the Gradle Wrapper executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Step 5: Execute the Gradle build
      - name: Build with Gradle
        run: ./gradlew build
